apiVersion: apps/v1
kind: Deployment
metadata:
 name: sonarqube
spec:
  selector:
    matchLabels:
     app: sonarqube
  replicas: 1
  podSecurityContext:
   {}
  template:
    metadata:
      name: sonarqube
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:latest
        resources:
          requests:
            cpu: 1000m
            memory: 1024Mi
          limits:
            cpu: 2000m
            memory: 4096Mi
        securityContext: 
          allowPrivilegeEscalation: false
        ports:
          - containerPort: 9000
            protocol: TCP
        volumeMounts:
        - mountPath: /opt/sonarqube/data/
          name: data
        - mountPath: /opt/sonarqube/extensions/
          name: extensions        
        - mountPath: /opt/sonarqube/conf
          name: conf
        - mountPath: /opt/sonarqube/logs/
          name: logs
      volumes:
      - name: data
        persistentVolumeClaim:
            claimName: data
      - name: extensions
        persistentVolumeClaim:
            claimName: extensions
      - name: conf
        persistentVolumeClaim:
            claimName: conf
      - name: logs
        persistentVolumeClaim:
            claimName: logs
       
       
        
    
---
apiVersion: v1
kind: Service
metadata:
    name: sonarqube
spec:
    selector: 
       app: sonarqube
    ports:
      - name: sonar
        port: 80
        targetPort: 9000
    type: LoadBalancer
